Format and quote input

diff --git a/bash/scripts/media b/bash/scripts/media
--- a/bash/scripts/media
+++ b/bash/scripts/media
@@ -1,6 +1,6 @@
 #!/bin/bash
 # default media player
-mpv="gnome-session-inhibit --inhibit idle mpv"
+mpv="gnome-session-inhibit --inhibit idle flatpak run io.mpv.Mpv"
 
 # filters
 DRC="acompressor=ratio=4,loudnorm"
@@ -17,37 +17,36 @@ reset_color=`tput sgr0`
 arguments=${@: 2} # argument string minus name and mode
 
 if ! command -v $mpv > /dev/null ; then
-  printf "%s not found.\n" "$mpv"
-  exit 1
+    printf "%s not found.\n" "$mpv"
+    exit 1
 fi
 
 case "$1" in
-  drc)
-    $mpv --af=$DRC "$arguments"
-    ;;
-  nm)
-    $mpv --af=lavfi=$NM "$arguments"
-    ;;
-  nmdrc)
-    $mpv --af=lavfi=$NMDRC "$arguments"
-    ;;
-  help)
-    printf "\n%s media filters\n" "${green}"
-    printf "%s drc\t%s dynamic range compression.\n" "${yellow}" "${reset_color}"
-    printf "%s nm\t%s night mode filter.\n" "${yellow}" "${reset_color}"
-    printf "%s nmdrc\t%s night mode with dynamic range compression.\n" "${yellow}" "${reset_color}"
-    printf "\n%s Options\n" "${green}"
-    printf "%s help\t%s print this screen.\n" "${yellow}" "${reset_color}"
-    printf "\nUsage: $0 %s drc %s | %s nm %s | %s nmdrc %s <file> <parameters>\n" "${cyan}" "${reset_color}" "${cyan}" "${reset_color}" "${cyan}" "${reset_color}"
-    exit 1
-    ;;
-  *)
-    if [[ ! $1 ]]; then
-      printf "%s * %stry:%s media %shelp%s\n" "${red}" "${green}" "${reset_color}" "${yellow}" "${reset_color}"
-      exit 1
-    fi
-    $mpv $1
-    ;;
+    drc)
+        $mpv --af=$DRC "$arguments"
+        ;;
+    nm)
+        $mpv --af=lavfi=$NM "$arguments"
+        ;;
+    nmdrc)
+        $mpv --af=lavfi=$NMDRC "$arguments"
+        ;;
+    help)
+        printf "\n%s media filters\n" "${green}"
+        printf "%s drc\t%s dynamic range compression.\n" "${yellow}" "${reset_color}"
+        printf "%s nm\t%s night mode filter.\n" "${yellow}" "${reset_color}"
+        printf "%s nmdrc\t%s night mode with dynamic range compression.\n" "${yellow}" "${reset_color}"
+        printf "\n%s Options\n" "${green}"
+        printf "%s help\t%s print this screen.\n" "${yellow}" "${reset_color}"
+        printf "\nUsage: $0 %s drc %s | %s nm %s | %s nmdrc %s <file> <parameters>\n" "${cyan}" "${reset_color}" "${cyan}" "${reset_color}" "${cyan}" "${reset_color}"
+        exit 1
+        ;;
+    *)
+        if [[ ! $1 ]]; then
+            printf "%s * %stry:%s media %shelp%s\n" "${red}" "${green}" "${reset_color}" "${yellow}" "${reset_color}"
+            exit 1
+        fi
+        $mpv "$1"
+        ;;
 esac
-
 
