Use mpv alias

diff --git a/zsh/functions/media b/zsh/functions/media
--- a/zsh/functions/media
+++ b/zsh/functions/media
@@ -1,6 +1,4 @@
-media(){
-  # default media player
-  MPLAYER="gnome-session-inhibit --inhibit idle flatpak run io.mpv.Mpv"
+media(){ 
   # filters
   DRC="acompressor=ratio=4,loudnorm"
   NM="[pan='stereo|FL=FC+0.30*FL+0.30*FLC+0.30*BL+0.30*SL+0.60*LFE|FR=FC+0.30*FR+0.30*FRC+0.30*BR+0.30*SR+0.60*LFE']"
@@ -16,23 +14,23 @@ media(){
   arguments=${@: 2} # argument string minus name and mode
 
   # This made sense before using flatpak
-  # if ! command -v $MPLAYER &> /dev/null ; then
-  #   printf "%s not found.\n" "$MPLAYER"
+  # if ! command -v mpv &> /dev/null ; then
+  #   printf "%s not found.\n" "mpv"
   #   return -1
   # fi
 
   case "$1" in
     drc)
-      $MPLAYER --af=$DRC "$arguments"
+      mpv --af="$DRC" "$arguments"
       ;;
     nofilter)
-      $MPLAYER $2
+      mpv $2
       ;;
     nm)
-      $MPLAYER --af=lavfi=$NM "$arguments"
+      mpv --af=lavfi="$NM" "$arguments"
       ;;
     nmdrc)
-      $MPLAYER --af=lavfi=$NMDRC "$arguments"
+      mpv --af=lavfi="$NMDRC" "$arguments"
       ;;
     help)
       printf "\n%s media filters\n" "${green}"
@@ -47,7 +45,7 @@ media(){
       if [[ ! $1 ]]; then
         printf "%s * %stry:%s media %shelp%s\n" "${red}" "${green}" "${reset_color}" "${yellow}" "${reset_color}"
       else
-        $MPLAYER $1
+        mpv "$1"
       fi
       ;;
   esac
